# Generated by Django 5.1.4 on 2024-12-21 15:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="job_description",
        ),
        migrations.RemoveField(
            model_name="application",
            name="job_link",
        ),
        migrations.RemoveField(
            model_name="application",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="historicalapplication",
            name="job_description",
        ),
        migrations.RemoveField(
            model_name="historicalapplication",
            name="job_link",
        ),
        migrations.RemoveField(
            model_name="historicalapplication",
            name="notes",
        ),
        migrations.AddField(
            model_name="application",
            name="cv",
            field=models.FileField(
                blank=True, null=True, upload_to=api.models.application_cv_upload_path
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="cv",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
